services:
    pgsql:
        image: 'postgres:18-alpine'
        container_name: infrastructure-pgsql
        ports:
            - '${FORWARD_DB_PORT:-5430}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-password}'
            POSTGRES_DB: '${DB_DATABASE:-lancore}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'infrastructure-pgsql:/var/lib/postgresql/data'
            - './init-databases.sh:/docker-entrypoint-initdb.d/10-create-databases.sh'
        networks:
            - lanparty
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE:-lancore}'
                - '-U'
                - '${DB_USERNAME:-sail}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: infrastructure-redis
        ports:
            - '${FORWARD_REDIS_PORT:-6370}:6379'
        volumes:
            - 'infrastructure-redis:/data'
        networks:
            - lanparty
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: infrastructure-mailpit
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8021}:8025'
        networks:
            - lanparty
    mockserver:
        image: 'mockserver/mockserver:latest'
        container_name: infrastructure-mockserver
        ports:
            - '1080:1080'
        networks:
            - lanparty

networks:
    lanparty:
        external: true

volumes:
    infrastructure-pgsql:
        driver: local
    infrastructure-redis:
        driver: local
